version: "3.0"

services:

  expcond-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expcond-api
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - .env

  expcond-rabbitmq:
    image: rabbitmq:3.9.21-alpine
    container_name: expcond-rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

volumes:
  grafana-storage:
